/** @fileOverview The entrypoint for generating OpenAPI Documentation */
import { flattenIO } from "./json-schema-helpers";

export type { Depicter } from "./documentation-helpers";
import {
  type InfoObject,
  type OperationObject,
  type ReferenceObject,
  type ResponsesObject,
  type SchemaObjectValue,
  type SecuritySchemeObject,
  type SecuritySchemeType,
  type ServerObject,
  OpenApiBuilder,
  type RequestBodyObject,
  isReferenceObject,
} from "openapi3-ts/oas32";
import * as R from "ramda";
import { type ResponseVariant, responseVariants } from "./api-response";
import { contentTypes } from "./content-type";
import { DocumentationError } from "./errors";
import {
  getInputSources,
  makeCleanId,
  normalizeParams,
} from "./common-helpers";
import type { CommonConfig } from "./config-type";
import { processContainers } from "./logical-container";
import type { ClientMethod } from "./method";
import {
  depictBody,
  depictRequestParams,
  depictResponse,
  depictSecurity,
  depictSecurityRefs,
  depictTags,
  trimSummary,
  reformatParamsInPath,
  nonEmpty,
  depictRequest,
  makeParamLocator,
  type IsHeader,
  type BrandHandling,
  excludeParamsFromDepiction,
} from "./documentation-helpers";
import type { Routing } from "./routing";
import { walkRouting, withHead, type OnEndpoint } from "./routing-walker";
import { z } from "zod";

export { DocumentationError };

type Component =
  | `${ResponseVariant}Response`
  | "requestParameter"
  | "requestBody";

/** @desc user defined function that creates a component description from its properties */
type Descriptor = (
  props: Record<"method" | "path" | "operationId", string> & {
    statusCode?: number; // for response only
  },
) => string;

type Summarizer = (params: {
  summary?: string;
  description?: string;
  trim: typeof trimSummary;
}) => string | undefined;

/** @desc Uses description as a fallback */
const defaultSummarizer: Summarizer = ({
  description,
  summary = description,
  trim,
}) => trim(summary);

interface DocumentationParams {
  /**
   * @desc The metadata about the API
   * @default { title: "Generated by Express Zod API", version: "0.0.0" }
   * */
  info?: InfoObject;
  /**
   * @desc Server URL(s) or their complete definitions
   * @default []
   * */
  server?: string | ServerObject | Array<string | ServerObject>;
  routing: Routing;
  config: CommonConfig;
  /**
   * @desc Descriptions of various components based on their properties (method, path, operationId).
   * @desc When composition set to "components", component name is generated from this description
   * @default () => `${method} ${path} ${component}`
   * */
  descriptions?: Partial<Record<Component, Descriptor>>;
  /**
   * @desc The function that ensures the maximum length for summary fields. Can optionally make them from descriptions.
   * @see defaultSummarizer
   * @see trimSummary
   * */
  summarizer?: Summarizer;
  /**
   * @desc Depict the HEAD method for each Endpoint supporting the GET method (feature of Express)
   * @default true
   * */
  hasHeadMethod?: boolean;
  /** @default inline */
  composition?: "inline" | "components";
  /**
   * @desc Handling rules for your own schemas branded with `x-brand` metadata.
   * @desc Keys: brands (recommended to use unique symbols).
   * @desc Values: functions having Zod context as first argument, second one is the framework context.
   * @example { MyBrand: ({ zodSchema, jsonSchema }) => ({ type: "object" })
   * @link https://www.npmjs.com/package/@express-zod-api/zod-plugin
   */
  brandHandling?: BrandHandling;
  /**
   * @desc Ability to configure recognition of headers among other input data
   * @desc Only applicable when "headers" is present within inputSources config option
   * @see defaultIsHeader
   * @link https://www.iana.org/assignments/http-fields/http-fields.xhtml
   * */
  isHeader?: IsHeader;
  /**
   * @desc Extended description of tags used in endpoints. For enforcing constraints:
   * @see TagOverrides
   * @example { users: "About users", files: { description: "About files", url: "https://example.com" } }
   * */
  tags?: Parameters<typeof depictTags>[0];
}

export class Documentation extends OpenApiBuilder {
  readonly #lastSecuritySchemaIds = new Map<SecuritySchemeType, number>();
  readonly #lastOperationIdSuffixes = new Map<string, number>();
  readonly #references = new Map<object | string, string>();
  readonly #visitedPaths = new Map<string, string>(); // normalized:original

  #makeRef(
    key: object | string,
    value: SchemaObjectValue | ReferenceObject,
    proposedName?: string,
  ): ReferenceObject {
    let name = this.#references.get(key); // search in the cache by the given key
    if (!name) {
      let inc = proposedName ? 0 : 1;
      do {
        name = `${proposedName ?? "Schema"}${inc ? this.#references.size + inc : ""}`;
        inc++;
      } while (this.rootDoc.components?.schemas?.[name]); // search in existing references for the unique name
      this.#references.set(key, name);
    }
    this.addSchema(name, value);
    return { $ref: `#/components/schemas/${name}` };
  }

  /**
   * @desc Resolves a ReferenceObject to the referenced schema. Non-reference input is returned as is.
   * @see getSpec
   * @example subject.resolve({ $ref: "#/components/schemas/UserInput" })
   * */
  public resolve<T extends SchemaObjectValue | z.core.JSONSchema.BaseSchema>(
    subject: T,
  ): T {
    let current = subject;
    const visited = new Set<string>(); // guarding against circular references
    while (isReferenceObject(current)) {
      if (visited.has(current.$ref)) return subject;
      visited.add(current.$ref);
      const resolved = R.path<T>(
        current.$ref.split("/").slice(1),
        this.rootDoc,
      );
      if (!resolved) return subject; // unresolvable reference
      current = resolved;
    }
    return current as T;
  }

  #ensureUniqOperationId(
    path: string,
    method: ClientMethod,
    userDefined?: string,
  ) {
    const operationId = userDefined || makeCleanId(method, path);
    let lastSuffix = this.#lastOperationIdSuffixes.get(operationId);
    if (lastSuffix === undefined) {
      this.#lastOperationIdSuffixes.set(operationId, 1);
      return operationId;
    }
    if (userDefined) {
      throw new DocumentationError(`Duplicated operationId: "${userDefined}"`, {
        method,
        isResponse: false,
        path,
      });
    }
    lastSuffix++;
    this.#lastOperationIdSuffixes.set(operationId, lastSuffix);
    return `${operationId}${lastSuffix}`;
  }

  #ensureUniqSecuritySchemaName(subject: SecuritySchemeObject) {
    const serializedSubject = JSON.stringify(subject);
    for (const name in this.rootDoc.components?.securitySchemes || {}) {
      if (
        serializedSubject ===
        JSON.stringify(this.rootDoc.components?.securitySchemes?.[name])
      )
        return name;
    }
    const nextId = (this.#lastSecuritySchemaIds.get(subject.type) || 0) + 1;
    this.#lastSecuritySchemaIds.set(subject.type, nextId);
    return `${subject.type.toUpperCase()}_${nextId}`;
  }

  #addMetadata({
    tags,
    server,
    info = { title: "Generated by Express Zod API", version: "0.0.0" },
  }: DocumentationParams) {
    this.addInfo(info);
    if (tags) this.rootDoc.tags = depictTags(tags);
    if (!server) return;
    for (const one of Array.isArray(server) ? server : [server])
      this.addServer(typeof one === "string" ? { url: one } : one);
  }

  #checkDuplicate(method: ClientMethod, path: string) {
    if (method === "head" || !path.includes(":")) return;
    const normalized = normalizeParams(path);
    const previous = this.#visitedPaths.get(normalized);
    if (previous !== undefined && previous !== path) {
      throw new DocumentationError(
        `Path has a duplicate: the normalized path "${normalized}" is already registered ` +
          `with different parameter names at "${previous}"`,
        { method, path, isResponse: false },
      );
    }
    if (previous === undefined) this.#visitedPaths.set(normalized, path);
  }

  #makeEndpointHandler({
    config,
    descriptions,
    brandHandling,
    isHeader,
    summarizer = defaultSummarizer,
    composition = "inline",
  }: DocumentationParams): OnEndpoint<ClientMethod> {
    const shared = {
      composition,
      brandHandling,
      makeRef: this.#makeRef.bind(this),
      seenIds: new Map<string, z.core.$ZodType>(),
    };
    return (method, path, endpoint) => {
      this.#checkDuplicate(method, path);
      const commons = { ...shared, path, method, endpoint };
      const { description, summary, scopes, inputSchema, security } = endpoint;
      const inputSources = getInputSources(method, config.inputSources);
      const { pathParams, getLocation } = makeParamLocator({
        method,
        path,
        security,
        inputSources,
        isHeader,
      });
      const operationId = this.#ensureUniqOperationId(
        path,
        method,
        endpoint.getOperationId(method),
      );

      const request = depictRequest({ ...commons, schema: inputSchema });
      const resolvedRequest = this.resolve(request);
      const flatRequest = flattenIO(resolvedRequest);
      const depictedParams = depictRequestParams({
        ...commons,
        getLocation,
        flatRequest,
        description: descriptions?.requestParameter?.({
          method,
          path,
          operationId,
        }),
      });
      if (pathParams.size) {
        throw new DocumentationError(
          `The input schema is missing the path parameter "${[...pathParams][0]}"`,
          { method, path, isResponse: false },
        );
      }

      const responses: ResponsesObject = {};
      for (const variant of responseVariants) {
        const apiResponses = endpoint.getResponses(variant);
        for (const { mimeTypes, schema, statusCodes } of apiResponses) {
          for (const statusCode of statusCodes) {
            responses[statusCode] = depictResponse({
              ...commons,
              variant,
              schema,
              mimeTypes,
              statusCode,
              hasMultipleStatusCodes:
                apiResponses.length > 1 || statusCodes.length > 1,
              description: descriptions?.[`${variant}Response`]?.({
                method,
                path,
                operationId,
                statusCode,
              }),
            });
          }
        }
      }

      let requestBody: RequestBodyObject | undefined = undefined;
      if (inputSources.includes("body")) {
        const paramNames = R.pluck("name", depictedParams);
        // When the whole request is a shared component reference and there is
        // nothing to strip, keep reusing that reference (#3570); otherwise
        // operate on the resolved subject so path params can be excluded (#3659)
        const bodySubject =
          !paramNames.length || resolvedRequest === request
            ? request
            : resolvedRequest;
        const [bodyJsonSchema, hasRequiredBodyProps] =
          excludeParamsFromDepiction(bodySubject, paramNames);
        requestBody = depictBody({
          ...commons,
          bodyJsonSchema,
          hasRequiredBodyProps,
          flatRequest,
          paramNames,
          mimeType: contentTypes[endpoint.getProbableRequestType(method)],
          description: descriptions?.requestBody?.({
            method,
            path,
            operationId,
          }),
        });
      }

      const securityRefs = depictSecurityRefs(
        depictSecurity(processContainers(security), inputSources),
        scopes,
        (securitySchema) => {
          const name = this.#ensureUniqSecuritySchemaName(securitySchema);
          this.addSecurityScheme(name, securitySchema);
          return name;
        },
      );

      const operation: OperationObject = {
        operationId,
        summary: summarizer({ summary, description, trim: trimSummary }),
        description,
        deprecated: endpoint.isDeprecated || undefined,
        tags: nonEmpty(endpoint.tags),
        parameters: nonEmpty(depictedParams),
        requestBody,
        security: nonEmpty(securityRefs),
        responses,
      };
      this.addPath(reformatParamsInPath(path), { [method]: operation });
    };
  }

  public constructor({ hasHeadMethod = true, ...rest }: DocumentationParams) {
    super();
    this.#addMetadata(rest);
    const handler = this.#makeEndpointHandler(rest);
    const onEndpoint = hasHeadMethod ? withHead(handler) : handler;
    walkRouting({ ...rest, onEndpoint });
  }
}
