packages:
  - express-zod-api
  - zod-plugin
  - migration
  - example
  - cjs-test
  - esm-test
  - compat-test
  - issue952-test
gitChecks: false
engineStrict: true
autoInstallPeers: false
minimumReleaseAge: 2880 # 2 days
minimumReleaseAgeExclude:
  - "@types/*"
  - "@eslint/*"
  - "@rolldown/*"
  - "@vitest/*"
  - "@typescript-eslint/*"
  - body-parser
  - eslint
  - eslint-plugin-allowed-dependencies
  - express
  - http-errors
  - import-without-cache
  - prettier
  - qs
  - ramda
  - raw-body
  - rolldown
  - rolldown-plugin-dts
  - typescript
  - typescript-eslint
  - tsdown
  - unrun
  - vite
  - vitest
  - zod
publicHoistPattern:
  - "@typescript-eslint/*" # used as an assumed transitive in migration
  - "@vitest/*" # used by vitest.setup.ts and vitest.config.ts
  - "@eslint/*" # used by eslint.config.js
  - "globals" # used by eslint.config.js
  - "@types/qs" # used by index.ts, fixes TS2742 for attachRouting
  - "@types/express-serve-static-core" # used by index.ts, fixes TS2742 for attachRouting
catalogs:
  prod:
    "ramda": "^0.32.0"
  peer:
    "zod": "^4.1.13"
  dev:
    "@types/compression": "^1.8.1"
    "@types/express": "^5.0.6"
    "@types/express-fileupload": "^1.5.1"
    "@types/http-errors": "^2.0.5"
    "@types/ramda": "^0.31.1"
    "@typescript-eslint/rule-tester": "^8.51.0"
    "camelize-ts": "^3.0.0"
    "compression": "^1.8.1"
    "express": "^5.2.1"
    "express-fileupload": "^1.5.2"
    "http-errors": "^2.0.1"
    "typescript": "^5.9.3"
    "typescript-eslint": "^8.51.0"
    "zod": "^4.3.4"
overrides:
  "@scarf/scarf": "npm:empty-npm-package@1.0.0"
  "lightningcss": "npm:empty-npm-package@1.0.0"
  "vite": "^8.0.0-beta.7"
