packages:
  - express-zod-api
  - zod-plugin
  - migration
  - example
  - cjs-test
  - esm-test
  - compat-test
  - issue952-test

autoInstallPeers: false

catalogs:
  dev:
    '@types/compression': ^1.8.1
    '@types/express': ^5.0.5
    '@types/express-fileupload': ^1.5.1
    '@types/http-errors': ^2.0.5
    '@types/ramda': ^0.31.1
    '@typescript-eslint/rule-tester': ^8.46.2
    camelize-ts: ^3.0.0
    compression: ^1.8.1
    express: ^5.1.0
    express-fileupload: ^1.5.2
    http-errors: ^2.0.0
    typescript: ^5.9.3
    typescript-eslint: ^8.46.2
    zod: ^4.1.12
  prod:
    ramda: ^0.32.0

engineStrict: true

gitChecks: false

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - '@types/*'
  - '@eslint/*'
  - '@rolldown/*'
  - '@vitest/*'
  - '@typescript-eslint/*'
  - eslint
  - eslint-plugin-allowed-dependencies
  - express
  - http-errors
  - ramda
  - rolldown
  - rolldown-plugin-dts
  - typescript
  - typescript-eslint
  - tsdown
  - tsx
  - vite
  - vitest
  - zod

onlyBuiltDependencies:
  - esbuild

overrides:
  '@scarf/scarf': npm:empty-npm-package@1.0.0

publicHoistPattern:
  - '@typescript-eslint/*'
  - '@vitest/*'
  - '@eslint/*'
  - globals
  - '@types/qs'
  - '@types/express-serve-static-core'
