packages:
  - express-zod-api
  - example
  - cjs-test
  - esm-test
  - issue952-test
onlyBuiltDependencies:
  - esbuild
gitChecks: false
engineStrict: true
publicHoistPattern:
  - "@typescript-eslint/*" # used by migration.ts
  - "@vitest/*" # used by vitest.setup.ts and vitest.config.ts
  - "@eslint/*" # used by eslint.config.js
  - "globals" # used by eslint.config.js
  - "@types/qs" # used by index.ts, fixes TS2742 for attachRouting
  - "@types/express-serve-static-core" # used by index.ts, fixes TS2742 for attachRouting
catalogs:
  peer:
    "@types/compression": "^1.7.5"
    "@types/express": "^5.0.0"
    "@types/express-fileupload": "^1.5.0"
    "@types/http-errors": "^2.0.2"
    "compression": "^1.8.0"
    "express": "^5.1.0"
    "express-fileupload": "^1.5.0"
    "http-errors": "^2.0.0"
    "typescript": "^5.1.3"
    "zod": "^3.25.35"
  dev:
    "undici": "^6.19.8"
