packages:
  - express-zod-api
  - example
  - cjs-test
  - esm-test
  - issue952-test
onlyBuiltDependencies:
  - esbuild
publicHoistPattern:
  - "@typescript-eslint/*"
  - "@vitest/*"
  - "@eslint/*"
  - globals
  - "@types/qs"
  - "@types/express-serve-static-core"
