packages:
  - express-zod-api
  - zod-plugin
  - migration
  - example
  - cjs-test
  - esm-test
  - compat-test
  - issue952-test

autoInstallPeers: false

catalogs:
  dev:
    '@types/compression': ^1.8.1
    '@types/express': ^5.0.3
    '@types/express-fileupload': ^1.5.1
    '@types/http-errors': ^2.0.5
    '@types/ramda': ^0.31.0
    '@typescript-eslint/rule-tester': ^8.40.0
    camelize-ts: ^3.0.0
    compression: ^1.8.1
    express: ^5.1.0
    express-fileupload: ^1.5.2
    http-errors: ^2.0.0
    typescript: ^5.9.2
    typescript-eslint: ^8.40.0
    zod: ^4.0.17
  prod:
    ramda: ^0.31.3

engineStrict: true

gitChecks: false

onlyBuiltDependencies:
  - esbuild

overrides:
  '@scarf/scarf': npm:empty-npm-package@1.0.0

publicHoistPattern:
  - '@typescript-eslint/*'
  - '@vitest/*'
  - '@eslint/*'
  - globals
  - '@types/qs'
  - '@types/express-serve-static-core'
