packages:
  - express-zod-api
  - zod-plugin
  - migration
  - example
  - cjs-test
  - esm-test
  - compat-test
  - issue952-test
gitChecks: false
engineStrict: true
autoInstallPeers: false
dedupePeers: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - eslint-plugin-allowed-dependencies # maintained by myself
  - zod@4.5.4 # verified by Socket Security
publicHoistPattern:
  - "@vitest/*" # used by vitest.setup.ts and vitest.config.ts
  - "@types/qs" # used by index.ts, fixes TS2742 for attachRouting
  - "@types/express-serve-static-core" # used by index.ts, fixes TS2742 for attachRouting
  - "zod" # used by tools/headers.ts
catalogs:
  prod:
    "ramda": "^0.32.0"
  peer:
    "zod": "^4.3.4"
  dev:
    "@types/compression": "^1.8.1"
    "@types/express": "^5.0.6"
    "@types/express-fileupload": "^1.5.1"
    "@types/http-errors": "^2.0.5"
    "@types/ramda": "^0.32.0"
    "camelize-ts": "^3.0.0"
    "compression": "^1.8.1"
    "express": "^5.2.1"
    "express-fileupload": "^1.5.2"
    "http-errors": "^2.0.1"
    "typescript": "npm:@typescript/typescript6@^6.0.2"
    "@typescript/native-preview": "npm:typescript@^7.0.2" # the name used by tsdown
    "zod": "^4.5.0"
overrides:
  "@scarf/scarf": "-"
  "lightningcss": "-"
