packages:
  - express-zod-api
  - zod-plugin
  - migration
  - example
  - cjs-test
  - esm-test
  - compat-test
  - issue952-test
onlyBuiltDependencies:
  - esbuild
gitChecks: false
engineStrict: true
autoInstallPeers: false
minimumReleaseAge: 2880 # 2 days
minimumReleaseAgeExclude:
  - "@types/*"
  - "@eslint/*"
  - "@rolldown/*"
  - "@vitest/*"
  - "@typescript-eslint/*"
  - eslint
  - eslint-plugin-allowed-dependencies
  - express
  - http-errors
  - ramda
  - rolldown
  - rolldown-plugin-dts
  - typescript
  - typescript-eslint
  - tsdown
  - tsx
  - vite
  - vitest
  - zod
publicHoistPattern:
  - "@typescript-eslint/*" # used as an assumed transitive in migration
  - "@vitest/*" # used by vitest.setup.ts and vitest.config.ts
  - "@eslint/*" # used by eslint.config.js
  - "globals" # used by eslint.config.js
  - "@types/qs" # used by index.ts, fixes TS2742 for attachRouting
  - "@types/express-serve-static-core" # used by index.ts, fixes TS2742 for attachRouting
catalogs:
  prod:
    "ramda": "^0.32.0"
  dev:
    "@types/compression": "^1.8.1"
    "@types/express": "^5.0.3"
    "@types/express-fileupload": "^1.5.1"
    "@types/http-errors": "^2.0.5"
    "@types/ramda": "^0.31.0"
    "@typescript-eslint/rule-tester": "^8.46.1"
    "camelize-ts": "^3.0.0"
    "compression": "^1.8.0"
    "express": "^5.1.0"
    "express-fileupload": "^1.5.1"
    "http-errors": "^2.0.0"
    "typescript": "^5.9.2"
    "typescript-eslint": "^8.46.1"
    "zod": "^4.0.0"
overrides:
  "@scarf/scarf": "npm:empty-npm-package@1.0.0"
