import type { Plugin } from "rolldown";
import { format, type Options } from "prettier";

const prettyOptions: Options = {
  parser: "typescript",
  printWidth: 120,
};

/** @desc Fixes weird formatting in the .d.ts files generated by tsdown v0.21 */
export default (): Plugin => ({
  name: "human-readable-dts-rolldown-plugin",
  generateBundle: async (_opt, bundle) => {
    for (const [name, file] of Object.entries(bundle)) {
      if (!(name.endsWith(".d.ts") && "code" in file)) continue;
      file.code = await format(
        file.code
          .replaceAll(/(\/\*\*[^\r\n]*?\*\/)/g, "\n$1\n") // ensure newlines around jsdoc
          .replaceAll(/\n\s*\n/g, "\n"), // rm double newlines
        prettyOptions,
      );
    }
  },
});
