import type { Rolldown } from "tsdown";
import { format } from "oxfmt";

/** @desc Fixes weird formatting in the .d.ts files generated by rolldown-plugin-dts v0.21 */
export const fixDtsPlugin = (): Rolldown.Plugin => ({
  name: "fix-dts-rolldown-plugin",
  generateBundle: async (_opt, bundle) => {
    for (const [name, file] of Object.entries(bundle)) {
      if (!(name.endsWith(".d.ts") && "code" in file)) continue;
      file.code = (
        await format(
          name,
          file.code.replaceAll(/\n\s*\n/g, "\n"), // rm double newlines
          { printWidth: 120 },
        )
      ).code;
    }
  },
});
