import type { Plugin } from "rolldown";
import { format, type FormatConfig } from "oxfmt";

const prettyOptions: FormatConfig = { printWidth: 120 };

/** @desc Fixes weird formatting in the .d.ts files generated by rolldown-plugin-dts v0.21 */
export const fixDtsPlugin = (): Plugin => ({
  name: "fix-dts-rolldown-plugin",
  generateBundle: async (_opt, bundle) => {
    for (const [name, file] of Object.entries(bundle)) {
      if (!(name.endsWith(".d.ts") && "code" in file)) continue;
      file.code = (
        await format(
          name,
          file.code
            .replaceAll(/^\/\/#(end)?region[^\r\n]*/gm, "") // rm rolldown comments
            .replaceAll(/#private;\s*/g, "") // rm #private markers (TS6 compatibility)
            .replaceAll(/\n\s*\n/g, "\n"), // rm double newlines
          prettyOptions,
        )
      ).code;
    }
  },
});
