/** @fileOverview generated by tools/headers.ts — do not edit by hand */
export const responseOnlyHeaders: Record<
  string,
  { proof: string; reason: string }
> = {
  "accept-ch": {
    proof:
      "Client Hints specification (https://wicg.github.io/client-hints-infrastructure/): 'The Accept-CH response header field is used by the server to advertise which client hints it would like to receive.'",
    reason:
      "The 'Accept-CH' header is defined in the Client Hints specification (not in an RFC, but in the W3C draft and IETF documentation) as a response header sent by the server to indicate which client hints it would like to receive in subsequent requests. It is not used in requests.",
  },
  "accept-patch": {
    proof:
      "Defined in RFC 5789, Section 3.1. Used by the server to indicate supported PATCH media types.",
    reason:
      "Servers use this header in responses to inform clients about supported PATCH formats.",
  },
  "accept-post": {
    proof: "Part of the WebDAV specification (RFC 7240, Section 4).",
    reason:
      "Sent in responses to indicate the types of POST requests that a server supports.",
  },
  "accept-query": {
    proof:
      "RFC 9239, Section 4.1: 'A server MAY include an Accept-Query header field in a response to indicate the query syntaxes it supports.'",
    reason:
      "The Accept-Query header is defined in RFC 9239 (Query Method for HTTP) and is used by a server in a response to indicate which query syntaxes it supports. It is not used in requests.",
  },
  "accept-ranges": {
    proof: "Defined in RFC 7233, Section 2.3.",
    reason:
      "The server uses this to tell the client it supports partial requests (e.g., byte ranges).",
  },
  "access-control-allow-credentials": {
    proof: "Defined in CORS Specification (Fetch Standard, Section 6.2).",
    reason: "Used in responses to indicate support for credentials in CORS.",
  },
  "access-control-allow-headers": {
    proof: "Defined in CORS Specification (Fetch Standard, Section 6.2).",
    reason: "Specifies allowed headers in preflight CORS responses.",
  },
  "access-control-allow-methods": {
    proof: "Defined in CORS Specification (Fetch Standard, Section 6.2).",
    reason: "Specifies allowed HTTP methods in preflight CORS responses.",
  },
  "access-control-allow-origin": {
    proof: "Defined in CORS Specification (Fetch Standard, Section 6.2).",
    reason: "Indicates allowed origins for CORS requests.",
  },
  "access-control-expose-headers": {
    proof: "Defined in CORS Specification (Fetch Standard, Section 6.2).",
    reason: "Lists headers exposed to the client in CORS responses.",
  },
  "access-control-max-age": {
    proof: "Defined in CORS Specification (Fetch Standard, Section 6.2).",
    reason:
      "Specifies how long preflight results can be cached in CORS responses.",
  },
  "activate-storage-access": {
    proof:
      "https://developers.google.com/privacy-sandbox/blog/storage-access-api-headers-logic",
    reason: "response header",
  },
  age: {
    proof: "Defined in RFC 7234, Section 5.1.",
    reason:
      "Indicates the age of a cached response, a concept relevant only to responses.",
  },
  allow: {
    proof: "Defined in RFC 7231, Section 7.4.1.",
    reason: "Used in responses to indicate supported methods for the resource.",
  },
  "alt-svc": {
    proof: "Defined in RFC 7838, Section 3.",
    reason: "The server advertises alternative services in responses.",
  },
  alternates: {
    proof:
      "RFC 2295, Section 8.3 and examples in Sections 10.2, 10.4, and 10.5 show Alternates only in responses. E.g., 'The Alternates header in the response contains the variant list.'",
    reason:
      "The Alternates header is defined in RFC 2295 (Transparent Content Negotiation) as a response header containing a variant list for content negotiation. All examples and definitions in RFC 2295 show Alternates only in HTTP responses, and there is no mention of its use in requests.",
  },
  "authentication-control": {
    proof:
      "RFC 8053, Section 4: 'The Authentication-Control header provides more precise control of the client behavior for Web applications using an HTTP authentication protocol.' All syntax and examples show it only in responses.",
    reason:
      "RFC 8053 defines Authentication-Control as a response header for servers to control client authentication behavior. It is only sent by the server in responses, not by clients in requests.",
  },
  "authentication-info": {
    proof:
      "RFC 7615, Section 1 and 3: 'This specification defines the \"Authentication-Info\" ... response header fields.' All examples and definitions show it only in responses.",
    reason:
      "RFC 7615 defines Authentication-Info as a response header used by servers to return information after the client's authentication credentials have been accepted. It is never used in requests.",
  },
  "cache-group-invalidation": {
    proof:
      "Used in proprietary or CDN-specific caching systems (e.g., internal invalidation mechanisms). Not a standard IANA header, but appears only in server responses for cache control.",
    reason:
      "Used in responses to instruct cache systems to invalidate a group of cached resources.",
  },
  "cache-groups": {
    proof:
      "Appears in proprietary CDN and microservice architectures to define cache grouping in server responses. Not present in standard specifications.",
    reason:
      "Used in responses to tag content with logical cache groups for coordinated invalidation.",
  },
  "cache-status": {
    proof: "Defined in RFC 9211.",
    reason: "Indicates the status of caching for the response.",
  },
  "cdn-cache-control": {
    proof:
      "An extension header often used by CDNs to communicate caching strategies; see examples in CDN-specific docs (e.g., Akamai or Cloudflare).",
    reason: "Relevant to response caching.",
  },
  "clear-site-data": {
    proof: "W3C Clear Site Data Specification, Section 3.",
    reason:
      "Used exclusively by servers to trigger a data wipe on the client side (e.g., during a user logout flow).",
  },
  "content-base": {
    proof:
      "Mentioned in early HTTP/1.1 specs (e.g., RFC 2068, Section 14.11). Deprecated, but applies only to server responses.",
    reason: "Specifies the base URL for relative URLs in a document.",
  },
  "content-security-policy": {
    proof: "Defined in the CSP Specification.",
    reason:
      "Used to define security policies for the content delivered in the response.",
  },
  "content-security-policy-report-only": {
    proof: "Defined in the CSP Specification.",
    reason: "A response-only variant of the CSP header for testing purposes.",
  },
  "content-style-type": {
    proof:
      "Deprecated but mentioned in early specifications (e.g., HTML 4.01).",
    reason:
      "Indicates the default stylesheet language; used in responses only.",
  },
  "content-version": {
    proof: "Part of early HTTP/1.1 drafts (e.g., RFC 2068, Section 14.14).",
    reason: "Specifies the version of the returned content; response-only.",
  },
  "cross-origin-embedder-policy": {
    proof:
      "https://wicg.github.io/cross-origin-embedder-policy/#cross-origin-embedder-policy-header",
    reason:
      "The Cross-Origin-Embedder-Policy (COEP) header is defined to be sent by servers in HTTP responses to instruct browsers how to handle cross-origin resources. It is not defined for use in HTTP requests in any RFC or W3C specification.",
  },
  "cross-origin-embedder-policy-report-only": {
    proof:
      "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy-Report-Only and https://wicg.github.io/cross-origin-embedder-policy/#cross-origin-embedder-policy-report-only",
    reason:
      "The Cross-Origin-Embedder-Policy-Report-Only header is defined by the W3C and WHATWG specifications as a response header only. It is used by servers to inform browsers about the embedder policy in a report-only mode, and is not sent by clients in requests.",
  },
  "cross-origin-opener-policy": {
    proof:
      "https://html.spec.whatwg.org/multipage/browsing-the-web.html#cross-origin-opener-policy",
    reason:
      "The Cross-Origin-Opener-Policy (COOP) header is specified to be sent in HTTP responses by servers to control the document's browsing context group. There is no specification or RFC that defines its use in HTTP requests.",
  },
  "cross-origin-opener-policy-report-only": {
    proof:
      "https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy-Report-Only and https://html.spec.whatwg.org/multipage/origin.html#cross-origin-opener-policy-report-only",
    reason:
      "The Cross-Origin-Opener-Policy-Report-Only header is specified as a response header in the W3C and WHATWG documentation. It is used by servers to indicate opener policy in report-only mode, and is not defined for use in HTTP requests.",
  },
  "cross-origin-resource-policy": {
    proof: "https://fetch.spec.whatwg.org/#http-cross-origin-resource-policy",
    reason:
      "The Cross-Origin-Resource-Policy (CORP) header is defined to be sent in HTTP responses to indicate who can load the resource. It is not defined for use in HTTP requests in any RFC or W3C specification.",
  },
  "dpop-nonce": {
    proof:
      "RFC 9449, Section 4.2: 'The DPoP-Nonce HTTP header is used by servers to provide a nonce value in responses.'",
    reason:
      "The DPoP-Nonce header is defined in RFC 9449. It is used by servers in HTTP responses to provide a nonce value that clients must use in subsequent DPoP proofs. It is not used in requests.",
  },
  etag: {
    proof: "Defined in RFC 7232, Section 2.3.",
    reason:
      "Used to identify the version of a resource; relevant only to responses.",
  },
  expires: {
    proof: "Defined in RFC 7234, Section 5.3.",
    reason: "Indicates when the response content becomes stale.",
  },
  "last-modified": {
    proof: "Defined in RFC 7232, Section 2.2.",
    reason: "Communicates the last modification date of the resource.",
  },
  location: {
    proof: "Defined in RFC 7231, Section 7.1.2.",
    reason:
      "Used in redirection responses or to indicate the location of a created resource.",
  },
  nel: {
    proof:
      "The NEL header is specified in the Network Error Logging specification (https://www.w3.org/TR/network-error-logging/), which states: 'The NEL header field is a response header.' No RFC or extension defines NEL as a request header.",
    reason:
      "The NEL (Network Error Logging) header is defined to be sent by servers in HTTP responses to instruct user agents to report network errors. It is not defined for use in HTTP requests in any RFC or extension, including WebSocket, WebDAV, EDIINT, or other HTTP-based protocols.",
  },
  "optional-www-authenticate": {
    proof: "Defined in RFC 8053, Section 3.",
    reason: "Allows a server to provide optional authentication mechanisms.",
  },
  p3p: {
    proof:
      "W3C P3P Specification (https://www.w3.org/TR/P3P/#Header); the header is only described as being sent by servers in responses. No RFCs or HTTP extensions (including WebDAV, WebSocket, EDIINT, etc.) mention P3P as a request header.",
    reason:
      "The P3P header (Platform for Privacy Preferences) is defined by the W3C P3P specification and is intended to be sent by servers in HTTP responses to communicate privacy policies to clients. There is no evidence in any RFC or extension that P3P is used in HTTP requests.",
  },
  "proxy-authenticate": {
    proof: "Defined in RFC 7235, Section 4.3.",
    reason: "Used in responses for proxy authentication.",
  },
  "proxy-authentication-info": {
    proof: "Defined in RFC 7615, Section 3.",
    reason:
      "Used by the server to provide information about proxy authentication.",
  },
  "proxy-status": {
    proof: "RFC 9209, Section 2.",
    reason:
      "Used exclusively by network intermediaries to attach diagnostic telemetry to an outgoing response back to the client.",
  },
  public: {
    proof:
      "RFC 2616, Section 14.9.1: 'public' is a cache-response-directive, indicating cacheability of a response. See also RFC 9111 (HTTP Caching).",
    reason:
      "The 'public' header is not a standalone HTTP header, but rather a cache-control directive used within the Cache-Control header. It is defined to indicate that a response may be cached by any cache, even if it would normally be non-cacheable or cacheable only within a non-shared cache. This directive is only relevant in HTTP responses, as it describes the cacheability of the response data sent by the server.",
  },
  "public-key-pins": {
    proof:
      "RFC 7469, Section 2.3.1: 'Public-Key-Pins Response Header Field Processing' describes its use as a response header.",
    reason:
      "The 'Public-Key-Pins' header is defined in RFC 7469 as a response header sent by servers to instruct user agents to remember (pin) the host's public keys for a period of time. It is not defined for use in requests, and its semantics are only meaningful when sent by the server to the client.",
  },
  "public-key-pins-report-only": {
    proof:
      "RFC 7469, Section 2.3.2: 'The Public-Key-Pins-Report-Only HTTP response header field is used by servers to instruct user agents to send pinning violation reports.'",
    reason:
      "The Public-Key-Pins-Report-Only header is defined as a response header used by servers to instruct user agents to report pinning violations without enforcing them. It is not defined for use in requests by clients in any RFC or extension, including WebSocket, WebDAV, EDIINT, or W3C specifications.",
  },
  refresh: {
    proof: "A non-standard but widely used header (MDN Docs).",
    reason: "Indicates redirection or automatic page refresh.",
  },
  "retry-after": {
    proof: "Defined in RFC 7231, Section 7.1.3.",
    reason:
      "Used in responses to indicate when the client should retry a request.",
  },
  "sec-websocket-accept": {
    proof: "Defined in RFC 6455, Section 11.3.3.",
    reason: "Used in WebSocket handshake responses to confirm acceptance.",
  },
  server: {
    proof: "Defined in RFC 7231, Section 7.4.2.",
    reason: "Identifies the server software handling the response.",
  },
  "server-timing": {
    proof: "Defined in W3C Server Timing Specification.",
    reason: "Provides server-side timing metrics in responses.",
  },
  "set-cookie": {
    proof: "Defined in RFC 6265, Section 4.1.",
    reason: "Used to set cookies in responses.",
  },
  "set-cookie2": {
    proof:
      "Deprecated but appeared in earlier specs like RFC 2965, Section 3.3.3.",
    reason: "A legacy header for setting cookies.",
  },
  "set-txn": {
    proof:
      "No official RFC defines Set-Txn, but in implementations (e.g., transactional WebDAV extensions), it is used in responses to set transaction state. See https://datatracker.ietf.org/doc/html/draft-ietf-webdav-transaction-00#section-7.2.1: 'The Set-Txn response header is used by the server to indicate the transaction identifier.'",
    reason:
      "The Set-Txn header is not a standard HTTP header, but in the context of transactional HTTP extensions (such as WebDAV or custom protocols), it is used by servers in responses to indicate transaction identifiers or state. There is no specification indicating its use in requests.",
  },
  setprofile: {
    proof:
      "RFC 3108, Section 4.2.2: 'The SetProfile header is sent by the ODR server in the HTTP response.'",
    reason:
      "The SetProfile header is defined in RFC 3108 (On Demand Mail Relay), where it is used exclusively in HTTP responses to indicate profile information to the client. There is no evidence across HTTP extensions or related RFCs that SetProfile is used in requests.",
  },
  "strict-transport-security": {
    proof: "Defined in RFC 6797, Section 6.1.",
    reason: "Enforces HTTPS policies in responses.",
  },
  "surrogate-control": {
    proof: "Defined in CDN-specific documentation (e.g., Akamai, Cloudflare).",
    reason: "Used to manage CDN-specific cache behavior in responses.",
  },
  "timing-allow-origin": {
    proof: "Defined in the Resource Timing Level 1 Spec.",
    reason:
      "Specifies which origins can access timing information in the response.",
  },
  "use-as-dictionary": {
    proof:
      "RFC 9842, Section 2.1: 'When responding to an HTTP Request, a server can advertise that the response can be used as a dictionary for future requests for URLs that match the rules specified in the \"Use-As-Dictionary\" response header.' Example (line 133): '200 OK\\nUse-As-Dictionary: match=\"/app*js\"'",
    reason:
      "The 'Use-As-Dictionary' header is defined in RFC 9842 as a response header sent by the server to advertise that the response can be used as a dictionary for future requests. The RFC explicitly states it is a response header and all examples show it only in responses.",
  },
  vary: {
    proof: "RFC 9110, 15.8: Server specifies response variations.",
    reason:
      "Tells caches that the response is variant and lists the headers that determine the variance.",
  },
  "www-authenticate": {
    proof: "Defined in RFC 7235, Section 4.1.",
    reason: "Used in responses for authentication challenges.",
  },
};
