name: Version Bump

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Workspace'
        required: true
        default: 'express-zod-api'
        type: choice
        options:
          - express-zod-api
          - migration
          - zod-plugin
      kind:
        description: 'Version bump kind'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

permissions:
  contents: write

jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - uses: fregante/setup-git-user@v2
      - run: |
          pnpm install
          pnpm install_hooks
      - name: Bump ${{inputs.workspace}} ${{inputs.kind}}
        working-directory: ${{inputs.workspace}}
        run: |
          pnpm version ${{inputs.kind}} \
            ${{ startsWith(inputs.kind, 'pre') && '--preid beta' || '' }} \
            --tag-version-prefix=${{inputs.workspace}}-v \
            --message='${{inputs.workspace}} version %s'
      - name: Push commit and tag
        run: git push --follow-tags
