name: Version Bump

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Workspace'
        required: true
        default: 'express-zod-api'
        type: choice
        options:
          - express-zod-api
          - migration
          - zod-plugin
      kind:
        description: 'Version bump kind'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

permissions:
  contents: write

jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # for git describe --tags (used by bumpp internally)
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
      - uses: fregante/setup-git-user@v2
      - run: |
          pnpm install
          pnpm install_hooks
      - name: Bumpp ${{inputs.workspace}}
        run: |
          pnpm -F ${{inputs.workspace}} exec \
            pnpm dlx bumpp ${{inputs.kind}} \
            ${{ startsWith(inputs.kind, 'pre') && '--preid beta' || '' }} \
            --tag=${{inputs.workspace}}-v%s --commit='${{inputs.workspace}} version %s' -y
