name: Compatibility test

on:
  push:
    branches: [ master, v20, v21, v22, v23 ]
  pull_request:
    branches: [ master, v20, v21, v22, v23 ]


jobs:
  Packing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build everything
        run: pnpm build
      - name: Pack express-zod-api
        run: pnpm -F express-zod-api pack --out compat-test/ez.tgz
      - name: Pack @express-zod-api/migration
        run: pnpm -F migration pack --out compat-test/migration.tgz
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: compat-test
  Minimum:
    needs: Packing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Add dependencies
        run: |
          yarn add express@5.1.0 typescript@5.1 http-errors@2.0.0 zod@3.25.35
          yarn add -D eslint@9.0.0 typescript-eslint@8.0.0 vitest tsx
          yarn add express-zod-api@./ez.tgz
          yarn add @express-zod-api/migration@./migration.tgz
      - name: Run tests
        run: |
          yarn eslint --fix
          yarn vitest
