name: Dependencies upgrade

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # Runs every 1st day of month at midnight UTC

permissions:
  contents: write  # Grants write access to push changes
  pull-requests: write # and create PRs

jobs:
  run-bash-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Upgrade dependencies
        # recursive, except the compat-test
        run: pnpm -F "\!compat-test" up

      - name: Branch name
        id: create-branch
        run: |
          BRANCH_NAME="deps-$(date +%Y-%m-%d)"
          echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ steps.create-branch.outputs.branch-name }}
          commit-message: "Upgrading all dependencies"
          title: "Upgrading all dependencies"
          body: "This PR contains automated updates generated by the monthly workflow."
          labels: "dependencies"
          assignees: "robintail"
          reviewers: "robintail"
