name: Minor

on: workflow_dispatch

permissions:
  contents: write

jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: fregante/setup-git-user@v2
      - run: |
          yarn install
          yarn install_hooks
      - run: npm version minor
