name: Minor

on: workflow_dispatch

permissions:
  contents: write

jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: fregante/setup-git-user@v1
      - run: |
          yarn install
          yarn install_hooks
      - run: npm version minor
