name: Minor

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Workspace'
        required: true
        default: 'express-zod-api'
        type: choice
        options:
          - express-zod-api
          - migration

permissions:
  contents: write

jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - uses: fregante/setup-git-user@v2
      - run: |
          pnpm install
          pnpm install_hooks
      - name: Bumpp ${{inputs.workspace}}
        run: |
          pnpm -F ${{inputs.workspace}} exec \
            pnpm dlx bumpp minor --tag=${{inputs.workspace}}-v%s -y
