name: Validations

on:
  push:
    branches: [ master, v18, v19, v20, v21 ]
  pull_request:
    branches: [ master, v18, v19, v20, v21 ]


jobs:
  OpenAPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Validate against OpenAPI 3.1
      #   uses: char0n/apidom-validate@v1
      #   with:
      #     definition-file: example/example.documentation.yaml
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install
      - run: yarn test:oas
      - name: Build
        run: yarn build
      - name: Pack artifact
        run: yarn workspace express-zod-api pack --filename dist.tgz
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: express-zod-api/dist.tgz
  Compatibility:
    needs: OpenAPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Install environment
        run: |
          cat >package.json <<EOF
          { "type": "module", "private": true }
          EOF
          yarn add express typescript http-errors zod
          yarn add eslint typescript-eslint vitest
      - name: Install artifact
        run: yarn add express-zod-api@./dist.tgz
      - name: Prepare migration test
        run: |
          cat >sample.ts <<EOF
          client.provide("get", "/v1/test", {id: 10});
          EOF
          cat >migration.spec.ts <<EOF
          import { readFile } from "node:fs/promises";
          describe("Migration", () => {
            test("should fix the import", async () => {
              const fixed = await readFile("./sample.ts", "utf-8");
              expect(fixed).toBe('client.provide("get /v1/test", {id: 10});\n');
            });
          });
          EOF
          cat >eslint.config.js <<EOF
          import parser from "@typescript-eslint/parser";
          import migration from "express-zod-api/migration";
          export default [
            { languageOptions: { parser }, plugins: { migration } },
            { files: ["**/*.ts"], rules: { "migration/v22": "error" } },
          ];
          EOF
      - name: Run migration test
        run: |
          yarn eslint --fix
          yarn vitest --globals
