name: Validations

on:
  push:
    branches: [ master, v18, v19, v20, v21 ]
  pull_request:
    branches: [ master, v18, v19, v20, v21 ]


jobs:
  OpenAPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Validate against OpenAPI 3.1
      #   uses: char0n/apidom-validate@v1
      #   with:
      #     definition-file: example/example.documentation.yaml
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install
      - run: yarn test:oas
      - name: Build
        run: yarn build
      - name: Pack artifact
        run: yarn workspace express-zod-api pack --filename dist.tgz
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: express-zod-api/dist.tgz
  Compatibility:
    needs: OpenAPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - run: |
          ls -la
          ls -la dist
