name: Validations

on:
  push:
    branches: [ master, v18, v19, v20, v21 ]
  pull_request:
    branches: [ master, v18, v19, v20, v21 ]


jobs:
  OpenAPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Validate against OpenAPI 3.1
      #   uses: char0n/apidom-validate@v1
      #   with:
      #     definition-file: example/example.documentation.yaml
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun test:oas
      - name: Build distribution
        run: bun -F express-zod-api build
      - name: Build tests
        run: bun postbuild # builds the tests
      - name: Pack artifact
        working-directory: express-zod-api
        run: bun pm pack --filename compat-test/dist.tgz
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: compat-test
  Compatibility:
    name: express@${{matrix.express-version}}
    needs: OpenAPI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        express-version: [ 4, 5 ]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Add dependencies
        run: |
          yarn add express@${{matrix.express-version}} typescript@5.1 http-errors zod
          yarn add -D eslint@9.0 typescript-eslint@8.0 vitest tsx
          yarn add express-zod-api@./dist.tgz
      - name: Run tests
        run: |
          yarn eslint --fix
          yarn vitest
